
project_id = "dmqkgahwnpvtzawncluv"

[api]
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
port = 54324

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "https://dmqkgahwnpvtzawncluv.supabase.co"
additional_redirect_urls = ["https://dmqkgahwnpvtzawncluv.supabase.co"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = true
enable_confirmations = false

[auth.sms.twilio]
enabled = false
account_sid = ""
message_service_sid = ""
auth_token = ""

[auth.external.apple]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.github]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.google]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[functions]
